name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Minikube Docker
        run: |
          minikube docker-env --shell powershell | Invoke-Expression

      - name: Build Backend Docker Image
        run: |
          cd backend
          docker build -t backend-app:latest .

      - name: Build Frontend Docker Image
        run: |
          cd dashboard
          docker build -t frontend-app:latest .

      - name: Apply Kubernetes Files
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Verify Pods
        run: kubectl get pods
